fix: node 404 (#40)
```
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:6ceb39cdb19984aed3125dff77678c77d136c40a492742a01d7aac6921e802ef
curl: (22) The requested URL returned error: 404
Error: node: Failed to download resource "node"
Download failed: https://ghcr.io/v2/homebrew/core/node/blobs/sha256:6ceb39cdb19984aed3125dff77678c77d136c40a492742a01d7aac6921e802ef
```

I suspect this is due to the change of name. Unsure how this will play
with the file being called `node.rb` 🤷 lets find out together